### ISSUE TITLE
Cacti are spawning wierd

### ISSUE THREAD

**Issue by Jigbashmop** [supermassimo/DynamicTeesPlus#1]
![20210618155920_1](https://user-images.githubusercontent.com/42393677/122610800-3b8c2980-d04e-11eb-83c8-8f4495384544.jpg)

**Comment by Harleyoc1** [comment]
This is not how they are spawning. It is a rendering issue. 

What version of DT+ and DT are you on?

**Comment by Jigbashmop** [comment]
Just made the pack today, should be the latest versions

**Comment by Harleyoc1** [comment]
Never say “latest” for versions in issue trackers. 

Anyway are you using sodium? Someone mentioned spoorn/sodium-forge#17 in the Discord which looks like it might be the same issue.

**Comment by Jigbashmop** [comment]
Sorry, I was on mobile and couldn't check the exact version. DynamicTrees-1.16.5-0.10.0-Beta16 and DynamicTreesPlus-1.16.5-0.1.0-Beta9 for reference.

Yes, I'm using Sodium Reforged (sodium-forge-2.2). It looks like the cacti work properly when cutting them down, they're just displaying oddly

**Comment by Harleyoc1** [comment]
OK well since it seems to be related to sodium we'll keep it in that issue I mentioned previously. Check back there for a solution.
