### ISSUE TITLE
Rendering problems

### ISSUE THREAD

**Issue by rjulib00** [supermassimo/DynamicTeesPlus#10]
when using magnesium, the rendering of the cactus are floating blocks, tried deactivate all options ingame but seems none is, do i have to change in a config file?
https://gyazo.com/9d93a1ef40c5b5fcccc21dec06da2d60
but when break is rendering correctly
https://gyazo.com/e9efe38c5a845ef5ae65fc8b486bb92e

**Comment by Harleyoc1** [comment]
This is a known incompatibility issue with Magnesium. Unfortunately we don't know of any solution at the moment. 

Anyway I'm going to keep this issue tracked on DynamicTreesTeam/DynamicTrees#658 as it is the same issue.
