### ISSUE TITLE
Sodium for Forge Render Conflict (1.16.5)

### ISSUE THREAD

**Issue by BreadBox64** [supermassimo/DynamicTeesPlus#12]
All ports of sodium to forge for 1.16.5 (Rubidium, Magnesium, Halogen) don't render cactus properly. The cactus all displays as a branch unconnected from all other sides, but still shows the correct hitbox (see images)

![2022-04-21_23 50 58](https://user-images.githubusercontent.com/62221340/164605857-ece7f677-01c8-4db3-9b28-6d3d2daa2c50.png)
![2022-04-21_23 53 45](https://user-images.githubusercontent.com/62221340/164605861-038910c6-3c71-47ed-b287-7e1f4ba66ce3.png)

**Comment by Harleyoc1** [comment]
Sodium Forge port issues will now be confined to this thread: DynamicTreesTeam/DynamicTrees#658
